### PR TITLE
lein-newnew

### PR DESCRIPTION
**Pull request by Raynes**
This ought to do it. Note that the first commit was from ages ago. The latter two are just updating it. Feel free to tweak as needed.

### CODE REVIEW

**Comment by Raynes** [comment]
Sorry it took so long btw.

**Comment by jszakmeister** [comment]
FYI: the resulting skeleton site gives a traceback when run.  The generated template isn't correct for the most recent versions of Noir.  It appears the skeleton is for 1.1.

**Comment by jszakmeister** [comment]
It was a pretty simple fix.  I've put the fix here: jszakmeister/lein-noir@825c0f2d9c9ac801273db6b3bf3f63f0f89477eb.

**Comment by technomancy** [comment]
If you change the defproject form to `noir/lein-template`, then it can be used without being added to the `:user` profile: https://github.com/Raynes/lein-newnew/issues/12

**Pull request merged**
