### PR TITLE
Clojure 1.3 compatibility

### PR DESCRIPTION
**Pull request by rplevy**
Very minor obvious change.  I didn't bump the version number. I think this would be a bump to the next minor version, but you decide.

### CODE REVIEW

**Comment by ibdknox** [comment]
Did you run this? Last I knew leiningen plugins couldn't use 1.3 since they're run in lein's process and lein must be on 1.2.\* right now.

**Comment by Raynes** [comment]
It _can_, but it doesn't have any effect IIRC.

**Comment by rplevy** [comment]
My mistake, I didn't know about this problem.  It was such a minor change (and it compiled) that I didn't think to try installing the plugin.  When I ran lein noir new foo, it resulted in this error:

Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchMethodError: clojure.lang.KeywordLookupSite.<init>(ILclojure/lang/Keyword;)V

Now I know why it's not already using 1.3!

**Comment by semperos** [comment]
This seems to be no longer an issue. I've just forked lein-noir, made the same changes as this pull request, ran `lein install` and then `lein plugin install lein-noir 1.2.1.1`, and am able to use lein-noir with Leiningen 1.x (I bumped my local version just to be sure I was using my changes).

**Comment by Raynes** [comment]
This will all be irrelevant anyways once this is made into a lein newnew template with the next release of noir.

**Comment by ibdknox** [comment]
should be fixed in 1.3.0

**Pull request closed without merging**
